### PR TITLE
Migrated the extension to manifest v3

### LINKED ISSUE #588: Need to update manifest to v3 before June 2024
per https://developer.chrome.com/blog/resuming-the-transition-to-mv3

### PR DESCRIPTION
**Pull request by fastndead**
In this PR I'm migrating the manifest version to v3. The migration to manifest v3 brings several benefits, including enhanced security, improved performance, and better support for modern web standards.

It also opens up some chrome APIs that aren't available for manifest v2 such as TabGroup APIs (https://developer.chrome.com/docs/extensions/reference/api/tabGroups)

This is the first time for me migrating from v2 to v3 so I'm not sure if I forgot something (feel free to let me know), but for my use case (basic hotkeying) this works just the same as v2 version.

closes #588

### CODE REVIEW

**Comment by crittermike** [comment]
Beautiful! I'm out this week but I'll take a deeper look next week.

**Comment by fastndead** [comment]
I got some time to actually test the shortcuts that i don't usually use and I found that most of them don't work with manifest v3 so I had to rewrite those. Most of the failed actions were due to outdated usage of `executeScript` API. I implemented my own wrapper over browser API and replaced outdated occurrences with the new one. 

I checked all the shortcuts and got only 2 that I couldn't really get working due to Content Security Policy restrictions, those are "javascript" from "misc" category and ability to run bookmarklets. Both of these allow user to run custom scripts and I don't think it's possible while [user scripts API](https://developer.chrome.com/docs/extensions/reference/api/userScripts) is in beta. 

I don't know if the fact that we can't run custom scripts is a dealbreaker to upgrade to Manifest v3, but here we are :)

I personally never run custom javascript and bookmarklets but I understand how that can be a big deal for some people so maybe we need to hold off the upgrade till user scripts API is ready. I guess it's your call, @crittermike 

I should point out that even though running js on command seem harmless it could possibly open some security vulnerabilities (probably, maybe?) since it's not allowed by Content Security Policy.

**Comment by crittermike** [comment]
> I don't know if the fact that we can't run custom scripts is a dealbreaker to upgrade to Manifest v3

Yeah I'd call that a deal breaker. A huge percentage of users rely on JS shortcuts - for a lot of folks, that's the only value the extension provides. You happen to have any idea when we can expect the user scripts API to land given that it's in 120 beta? I'm confused/ignorant about how Chrome does their versioning since 120 is the stable channel for desktop so I'd expect beta features to be in 121...?

**Comment by crittermike** [comment]
Did you already try the approach described here? https://stackoverflow.com/questions/70474845/inject-javascript-from-content-script-with-a-chrome-extension-v3

**Comment by fastndead** [comment]
@crittermike I figured that JS shortcuts would be a deal breaker. I'd have to look into ways to overcome restrictions without violating chrome marketplace policies
Regarding userscripts release I'll have to get back to you on that since I am just as confused/ignorant as you are :) but I will gladly research that topic the moment I get a chance

**Comment by fastndead** [comment]
@crittermike Hey! I just added support for custom JS and bookmarklets, I will need to test it some more probably later, but for now all seem to be working. Thanks for referring me to StackOverflow question because it seems like most of Chrome API documentation resides in there and NOT in the official docs lol. I managed to solve the problem by introducing inject script that i inject into the page MAIN "world" that awaits for custom page events and i send events from the service_worker and content_scripts.

Regarding userscripts API i don't think it's productive to even look into that direction, I guess it was introduced in v120-beta and has been only in the beta world since, it has very limited support so i didn't even look into it further.

**Comment by crittermike** [comment]
I haven't investigated yet, but any idea off the top of your head why the icons aren't loading for me? 
image

**Comment by fastndead** [comment]
@crittermike yeah i noticed it too, it's probably has something to do with webextension-toolbox upgrade. also the fact that there's no initial shortcut uppon launching is a known issue. i'm going to fix that and regress test that extension later, maybe this weekend

**Comment by fastndead** [comment]
@crittermike hey! I fixed the icons and other small issues, tested every single shortcut and it seem to work fine! I wasn't able to test some of the functionality, i reflected the shortcuts in the `test_checklist.md`.
Those are the use cases that I wasn't able to properly test: 
1. The one for Tribal Wars players – I honestly didn't understand what is the expected behaviour 😅
2. Open App one – I couldn't figure out how to get the ID of the chrome apps. I have few installed, but they are not listed in my extension management page. I think the instructions for this shortcut might be outdated
3. Noop one – Maybe i don't understand something but for me it doesn't work even on the production version (i tried to cancel cmd+t and ctrl+tab shortcuts)

**Comment by crittermike** [comment]
Amazing! Merged it! You're the best.

I'll do a bit more testing on my end and then release it. Any reason to think upgrade path may be an issue for anyone?

**Comment by fastndead** [comment]
@crittermike honestly i think it works just the same for me, JS actions, which are a big deal as i understand, work perfect, so I think it should be all good, fingers crossed! :)

if this is released I think it would be good idea to add some actions for working with tab groups, what do you think? That's basically the whole point why i started whole this thing to be honest

**Pull request merged**
